dist: focal
language: python
sudo: required
addons:
  chrome: stable
env:
  global:
  - secure: bx4jocxpUDAveKsuCZuJ1zRrHcCY3C05Gr8sd+X0d0wnuh61QwPj+7q35Y+PVRVCjkcpbiUJ1JrfK4jvNoJUdY1hLUwd8NttgE4wfDDVjCUQGJecwkYG22PKvlImP/z+WpvzcELb+tyPpQ/V3vfldbLRIILwkPfwC1W5Kj87pv8=
#Tokens: CODACY_PROJECT_TOKEN
matrix:
  fast_finish: true
  include:
  - env: GLTEST='test' CODACY=true
  - env: GLTEST='build_and_install' DISTRIBUTION='bullseye'
  - env: GLTEST='build_and_install' DISTRIBUTION='focal'
before_install:
- nvm install --lts
- nvm use --lts
install: true
script:
- "$TRAVIS_BUILD_DIR/travis/script.sh"
notifications:
  slack:
    secure: KhvVUD69Pq/0ZuQyug+NfH8LXLwFNlBQmhgAx6woYtnpGwq5KqMl4lpNeb1dKptUlJen+iAQRwO6nqAzWL92eO9qSCSLZDvKS0qDtMUAI9ax1cJ/G8K/Ee6vILU6id37VtwHFD4cJQPxZOZoDXoNcO6PRGVJDFt6JTGsOroexCI=
